### PR TITLE
Thank me later

### PR DESCRIPTION
**Pull request by Xx-Mohit-xX**
Now it will reply to messages and disabled mentions, test it in bot and let me know if it works or not

### CODE REVIEW

**Comment by Rahuletto** [comment]
Thank u.. but I already added in the npm. Not in github.

**Comment by Xx-Mohit-xX** [comment]
Alr, ill try to do it before you do next time

**Comment by Rahuletto** [comment]
So can I close this pr ?

**Comment by Xx-Mohit-xX** [comment]
> So can I close this pr ?

**Pull request closed without merging**
