### PR TITLE
Fixed the "Interaction failed" bug and added proper error messages

### PR DESCRIPTION
**Pull request by KK-Designs**
In the main games, I fixed the "! Interaction failed" error. This will take care of them for the `calculator`, `tictactoe`, `rps`, and `embed`. You can use my additions for everything else that this PR doesn't cover.

### CODE REVIEW

**Comment by A-K-O-R-A** [comment]
Is my GitHub bugging or did u delete most of the code in some files?

**Comment by KK-Designs** [comment]
I only removed the `let filter` and added? I also see it for some reason, dk why

**Comment by A-K-O-R-A** [comment]
Yeah I think the view in the app is just a bit buggy, will look at it from my PC later

**Comment by KK-Designs** [comment]
ok

**Comment by Rahuletto** [comment]
Actually already fixed those in dev branch.. npm update coming soon 👍

**Pull request closed without merging**
