### PR TITLE
if the cache does not have logchannel, fetch it

### PR DESCRIPTION
**Pull request by TechPro424**
# Checks
Yes, it does work as intended.

### CODE REVIEW

**Comment by A-K-O-R-A** [comment]
U need a `await` otherwise `fetch` will return a Promise

**Comment by TechPro424** [comment]
You don't need to await it
I use it in my bot's welcome function without await
Also, `fetch` does return only one channel, as you can provide only one channel id

**Comment by A-K-O-R-A** [comment]
Ok yeah that with the one channel was me being kinda stupid bcs i was in a hurry, but how Tf does it work without a await statement, like it will return a Promise not a Channel

**Comment by TechPro424** [comment]
> Ok yeah that with the one channel was me being kinda stupid bcs i was in a hurry, but how Tf does it work without a await statement, like it will return a Promise not a Channel
> 
> At least that's what the docs say
> 
> https://discord.js.org/#/docs/main/stable/class/GuildChannelManager?scrollTo=fetch

The example in the docs themselves doesnt have `await`
Ik it'll work cuz I've used it myself

**Comment by A-K-O-R-A** [comment]
Ok excuse me, I guess you are smarten than me, sorry for bothering you then.

**Comment by A-K-O-R-A** [comment]
grafik
I wonder how, i wonder why

**Comment by A-K-O-R-A** [comment]
After having a more detailed look into it, and changing a bit of code, this for example could work:
```js
const Discord = require('discord.js')

/**
 --- options ---
 
  credit => Boolean
  embedFoot => String
  embedDesc => String
  embedColor => HexColor
  embed => Embed
  logChannel => (Channel ID) String
 */

/**
 * @param {Discord.Message} message
 * @param {import('../index').ghostPingOptions} options
 */

async function ghostPing(message, options = []) {
  if (message.author.bot) return
  if (message.mentions.users.size < 1) return

  if (options.credit === false) {
    foot = options.embedFoot || 'Ghost Ping. Oop.'
  } else {
    foot = '©️ Simply Develop. npm i simply-djs'
  }

  try {
    const pingedMember = message.mentions.members.first()

    const chEmbed = new Discord.MessageEmbed()
      .setTitle('Ghost Ping Detected')
      .setDescription(
        options.embedDesc ||
          `I Found that ${message.author} **(${
            message.author.tag
          })** just ghost pinged ${pingedMember.toString()} **(${
            pingedMember.user.tag
          })**\n\nContent: **${message.content}**`
      )
      .setColor(options.embedColor || 0x075fff)
      .setFooter(foot)
      .setTimestamp()

    const msg = await message.channel.send({
      embeds: [options.embed || chEmbed]
    })

    if (options.logChannel) {
      const ch = await message.guild.channels.fetch(options.logChannel, {
        cache: true
      })

      await ch.send({ embeds: [options.embed || chEmbed] })
    }
    setTimeout(() => {
      msg.delete()
    }, 10000)
  } catch (err) {
    console.log(`Error Occured. | ghostPing | Error: ${err.stack}`)
  }
}
module.exports = ghostPing
```

**Comment by Rahuletto** [comment]
Should i merge akora ?

**Pull request closed without merging**
