### PR TITLE
Fixed every .setFooter() text object warning.

### PR DESCRIPTION
**Pull request by jebediah47**
# Information
All of the `.setFooter()` `Discord#MessageEmbed` options will include the `{ text: }` parameter after all the commits because this package uses the deprecated version of `.setFooter()` without the text param

# Issue Related
The issue is that the `.setFooter()` option without the text parameter is getting deprecated and so this PR will fix that by passing the text param to every single file that uses `.setFooter()`

# Checks
The package works as intended and no deprecation errors are thrown.

### CODE REVIEW

**Comment by Rahuletto** [comment]
Im sad to say that we have already re did everything on the package in the typescript branch

**Comment by Rahuletto** [comment]
Maybe u can test out our typescript branch and find out any bugs.

**Comment by jebediah47** [comment]
> Maybe u can test out our typescript branch and find out any bugs.

ok great I will do it, i'm closing the PR

**Comment by Rahuletto** [comment]
You can do PRs in typescript branch if u find any bug ♥️

**Pull request closed without merging**
