### PR TITLE
Update tictactoe.js

### PR DESCRIPTION
**Pull request by UnknownKID69**
+ Added check for BOTS since they can't accept challenge
+ Removed filter from confirmation since it was creating "Interaction failed" and added a message that only {opponent} can confirm it
+ Removed filter and max:1 from the actual game since it was creating "Interaction failed" and was preventing the message that " wait for your selection"

### CODE REVIEW

**Comment by A-K-O-R-A** [comment]
Looks good to me

**Comment by Rahuletto** [comment]
Will check the code after the school 🥲

**Comment by Rahuletto** [comment]
Done 👍

**Comment by UnknownKID69** [comment]
Yo u forgot the bot check again

**Comment by Rahuletto** [comment]
Oh sorry I only did bot check for rps 🤦 my bad.. will do it

**Pull request closed without merging**
