### PR TITLE
Fixed typescript errors in package

### PR DESCRIPTION
**Pull request by jebediah47**
---
name: Pull Request
about: Improve the package by contributing.
title: 'Pull Request'
labels: 'pr'
assignees: ''
---

# Description

Fixed the TypeScript issues that required // @ts-ignore and created interfaces for them so they don't error out! P.S also fixed a typo in line 327.

# Screenshots

If applicable, add screenshots to help explain the things changed.

# Issue Related

No issues related just wanted to help out!

# Checks

The (calc) function of the package works as intended!

### CODE REVIEW

**Comment by Rahuletto** [comment]
Can I see what was the error ?

Because I never encountered it

**Comment by jebediah47** [comment]
> Can I see what the error was ?
> 
> Because I never encountered it

It was not an error, the changes are made to remove unneeded @ts-ignores, the changes are just for a better coding practice. But the errors occur when "strict" mode is enabled in tsconfig

**Comment by jebediah47** [comment]
The title was my mistake, apologies.

**Comment by Rahuletto** [comment]
No problem

**Comment by Rahuletto** [comment]
But these are used all over the package and not only in calc.ts 😳

**Comment by jebediah47** [comment]
> But these are used all over the package and not only in calc.ts flushed

I can fix these types of errors throughout the package if you want me to do so (mind you it will take a bit)

**Comment by Rahuletto** [comment]
If u are ready to do, u can do it. I don't mind 😂

**Comment by jebediah47** [comment]
> If u are ready to do, u can do it. I don't mind joy

Ok I am turning this PR to work in progress and in a few hours I'll be probably done!

**Comment by jebediah47** [comment]
## Short description of what I did
There is no short description that can explain everything that I did, but in short terms I saw that the package had a lot of type errors which used @ts-ignore to be ignored by the TypeScript compiler, and most of those TypeErrors could have been fixed with 2 new interfaces. So I created 2 interfaces named `ExtendedInteraction` and `ExtendedMessage` which added type inferences for same types that emitted errors, the vanilla discord.js interfaces of those have been kept wherever possible, as you'll see from the changes, to reduce complication. From my side I did testing for all of the package's functions on my bot [galactica-bot](https://github.com/jebediah47/galactica-bot). Any file changes are welcome if I've made a mistake.

### My future contribution plans
This project is amazing and my aim from now on is to optimize it and improve it in any way possible because this project has future ahead of it! I really appreciate if you read until here!

**Comment by jebediah47** [comment]
@Rahuletto @A-K-O-R-A I think the PR is ready for you review!

**Comment by Rahuletto** [comment]
It's lookin good to me, what about you @A-K-O-R-A ?

**Comment by Rahuletto** [comment]
And thank you so so so much for helping us out by contributing, this meant a lot ♥️

**Review by A-K-O-R-A — COMMENTED** [review]
Looks good, maybe you could add a JSDoc string to the Extended Interfaces explaining what they do/why they exist. I think otherwise this may be confusing for future contributors as it isn't directly clear what the interfaces do.
Other than that great pr, thanks for the effort and the time you put into this <3

**Comment by jebediah47** [comment]
> Looks good, maybe you could add a JSDoc string to the Extended Interfaces explaining what they do/why they exist. I think otherwise this may be confusing for future contributors as it isn't directly clear what the interfaces do. Other than that great pr, thanks for the effort and the time you put into this <3

ok imma add the JSdoc in a bit!

**Comment by jebediah47** [comment]
ok good to go!

Also I will add some more changes to get your codefactor from `F` that it is now to C, B or even A!!

**Comment by jebediah47** [comment]
@Rahuletto @A-K-O-R-A the PR is ready for review!

**Comment by Rahuletto** [comment]
I feel so bad. Because I don't want people to help me. I don't want someone to suffer for me. This is just my inner self. 

Anyway, Thank you very much for helping us out 🎯

**Comment by Rahuletto** [comment]
Are we ready to push this ?

**Comment by jebediah47** [comment]
> I feel so bad. Because I don't want people to help me. I don't want someone to suffer for me. This is just my inner self.
> 
> Anyway, Thank you very much for helping us out dart

No worries in a few hours, I have a surprise for u 😜

**Comment by Rahuletto** [comment]
> Are we ready to push this ?

Uh ??

**Comment by jebediah47** [comment]
> > Are we ready to push this ?
> 
> Uh ??

If you are saying that to me, yeah that's about it!

**Comment by jebediah47** [comment]
Also @Rahuletto can you send me your discord for me to add you (if you don't want to send it here send it to this email: jebediah47@protonmail.com)

**Comment by Rahuletto** [comment]
I have my discord tag all over my projects 😂. Its ok, `Rahuletto#0243`

**Comment by jebediah47** [comment]
> Rahuletto#0243

I'm jeb47#3799

**Pull request merged**
